# Generated by Django 2.2.19 on 2022-04-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20220318_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите группу для публикации сообщения",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="group_post",
                to="posts.Group",
                verbose_name="Группа сообщения",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                help_text="Напечатайте сообщение", verbose_name="Текст поста"
            ),
        ),
    ]
