# Generated by Django 2.2.19 on 2022-04-25 05:17

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20220425_0458'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(
                check=models.Q(
                    _negated=True,
                    user=django.db.models.expressions.F('author'),
                ),
                name='prevent_self_follow_rule',
            ),
        ),
    ]
